"""empty message

Revision ID: 9f23f3c51afe
Revises: faa04e01cad0
Create Date: 2022-05-15 18:23:39.476932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f23f3c51afe'
down_revision = 'faa04e01cad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usuarios', ['celular'])
    op.execute("ALTER TABLE usuarios DROP CONSTRAINT usuarios_correo_key;")
    op.execute("ALTER TABLE usuarios ADD CONSTRAINT usuario_correo_pk PRIMARY KEY (correo);")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.execute("ALTER TABLE usuarios DROP CONSTRAINT usuario_correo_pk;")
    # ### end Alembic commands ###
