"""empty message

Revision ID: db829d14a640
Revises: 
Create Date: 2022-05-10 16:49:12.849140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db829d14a640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('clave', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('celular', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('usuario')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('talla', sa.String(length=3), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('distrito', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['usuario'], ['usuarios.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
