"""empty message

Revision ID: f721b85e8e38
Revises: db829d14a640
Create Date: 2022-05-14 12:58:12.711506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f721b85e8e38'
down_revision = 'db829d14a640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('productos_usuario_fkey', 'productos', type_='foreignkey')
    op.add_column('productos', sa.Column('usuario_correo', sa.String(length=80), nullable=False))
    op.drop_column('productos', 'usuario')
    op.add_column('usuarios', sa.Column('correo', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'usuarios', ['correo'])
    op.drop_column('usuarios', 'usuario')
    op.create_foreign_key(None, 'productos', 'usuarios', ['usuario_correo'], ['correo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('usuario', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'correo')
    op.add_column('productos', sa.Column('usuario', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.create_foreign_key('productos_usuario_fkey', 'productos', 'usuarios', ['usuario'], ['usuario'])
    op.drop_column('productos', 'usuario_correo')
    # ### end Alembic commands ###
